version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ip-geo-locator-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  ip-geo-locator-app:
    build: .
    container_name: ip-geo-locator-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379